-- db/extensions.sql
-- Persistent derived intelligence tables
-- NOT rebuilt on every analytics refresh — updated by intelligence pipelines
--
-- Canonical definitions for:
--   · ideology_scores        (PCA + clustering output)
--   · sponsorship_scores     (network centrality metrics)
--   · bill_lineage           (resurrection / similarity graph)
--   · caucus_clusters        (human-readable cluster labels)
--

PRAGMA foreign_keys = ON;

-- ─────────────────────────────────────────────────────────────────────────────
-- IDEOLOGY SCORES  (PCA + clustering output)
-- ─────────────────────────────────────────────────────────────────────────────
-- Replaces the split between member_ideology_profiles (analytics.sql) and
-- ideology_scores (extensions.sql). One table; analytics.sql no longer
-- defines member_ideology_profiles.

CREATE TABLE IF NOT EXISTS ideology_scores (
    member_id       INTEGER PRIMARY KEY REFERENCES members(member_id),
    session_id      TEXT,

    -- PCA axes (labels generated by the pipeline, not fixed)
    axis1_value     REAL,
    axis1_label     TEXT,   -- e.g. "Establishment ↔ Maverick"
    axis2_value     REAL,
    axis2_label     TEXT,   -- e.g. "Partisan ↔ Coalition Builder"
    axis3_value     REAL,   -- third axis when variance warrants it

    caucus_cluster  INTEGER REFERENCES caucus_clusters(cluster_id),
    ideology_label  TEXT,   -- synthesized human-readable label

    -- Derived scores
    polarity_score  REAL,   -- partisan polarity (-1 left … +1 right)
    maverick_score  REAL,   -- frequency of voting against party majority
    confidence      REAL,   -- model confidence 0–1

    updated_at      TEXT
);
CREATE INDEX IF NOT EXISTS idx_ideology_cluster ON ideology_scores(caucus_cluster);
CREATE INDEX IF NOT EXISTS idx_ideology_session ON ideology_scores(session_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- SPONSORSHIP / NETWORK SCORES
-- ─────────────────────────────────────────────────────────────────────────────
-- Replaces the split between member_network_metrics (analytics.sql) and
-- sponsorship_scores (extensions.sql).

CREATE TABLE IF NOT EXISTS sponsorship_scores (
    member_id           INTEGER PRIMARY KEY REFERENCES members(member_id),
    session_id          TEXT,

    -- Graph centrality (computed over cosponsor_network)
    degree_centrality   REAL,
    betweenness         REAL,
    closeness           REAL,
    eigenvector         REAL,
    bridge_score        REAL,   -- structural hole / broker metric
    influence_score     REAL,   -- weighted composite

    -- Cross-party collaboration
    bipartisan_score    REAL,   -- cross-party cosponsor rate

    community_id        INTEGER,

    updated_at          TEXT
);
CREATE INDEX IF NOT EXISTS idx_sponsorship_influence ON sponsorship_scores(influence_score DESC);
CREATE INDEX IF NOT EXISTS idx_sponsorship_community ON sponsorship_scores(community_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- BILL LINEAGE  (resurrection / similarity graph)
-- ─────────────────────────────────────────────────────────────────────────────
-- Canonical single definition. Columns unified from the two previously
-- conflicting definitions (source_bill_pk vs parent_bill_pk, etc.).

CREATE TABLE IF NOT EXISTS bill_lineage (
    lineage_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    source_bill_pk      INTEGER REFERENCES bills(bill_pk),
    related_bill_pk     INTEGER REFERENCES bills(bill_pk),
    source_version_id   INTEGER REFERENCES bill_versions(version_id),
    related_version_id  INTEGER REFERENCES bill_versions(version_id),
    similarity_score    REAL,
    method              TEXT CHECK(method IN ('minhash','jaccard','hybrid','manual')),
    -- reintroduced / modeled_after / amended_from / substitute / copy / zombie
    relation_type       TEXT,
    detected_at         TEXT,
    UNIQUE(source_bill_pk, related_bill_pk)
);
CREATE INDEX IF NOT EXISTS idx_lineage_source ON bill_lineage(source_bill_pk);
CREATE INDEX IF NOT EXISTS idx_lineage_target ON bill_lineage(related_bill_pk);
CREATE INDEX IF NOT EXISTS idx_lineage_score  ON bill_lineage(similarity_score DESC);


-- ─────────────────────────────────────────────────────────────────────────────
-- CAUCUS CLUSTERS
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS caucus_clusters (
    cluster_id      INTEGER PRIMARY KEY,
    cluster_name    TEXT,
    description     TEXT,
    dominant_party  TEXT,
    size            INTEGER,
    session_id      TEXT,
    updated_at      TEXT
);


-- ─────────────────────────────────────────────────────────────────────────────
-- PERFORMANCE INDEXES
-- (Additional indexes over core tables — safe to apply after schema.sql)
-- ─────────────────────────────────────────────────────────────────────────────

-- Vote analytics hot paths
CREATE INDEX IF NOT EXISTS idx_mv_member_roll   ON member_votes(member_id, roll_call_id);
CREATE INDEX IF NOT EXISTS idx_rc_session_ctx   ON roll_calls(session_id, vote_context);

-- Sponsorship graph builds
CREATE INDEX IF NOT EXISTS idx_bs_member        ON bill_sponsors(member_id);
CREATE INDEX IF NOT EXISTS idx_bs_bill          ON bill_sponsors(bill_pk);

-- Bill similarity scans
CREATE INDEX IF NOT EXISTS idx_bill_text        ON bills(title, short_desc);

-- Change event acceleration
CREATE INDEX IF NOT EXISTS idx_event_entity_pk  ON change_events(entity_pk);

-- ─────────────────────────────────────────────────────────────────────────────
-- LANGUAGE FRAGMENTS
-- Sub-bill units of text (sections/passages) for partial-match lineage
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS bill_language_fragments (
    fragment_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    bill_pk         INTEGER NOT NULL REFERENCES bills(bill_pk) ON DELETE CASCADE,
    version_id      INTEGER REFERENCES bill_versions(version_id),
    session_id      TEXT NOT NULL REFERENCES sessions(session_id),
    fragment_index  INTEGER NOT NULL,       -- ordinal within bill (0-based)
    fragment_type   TEXT,                   -- 'section' | 'paragraph' | 'passage'
    char_offset     INTEGER,                -- byte offset in full_text for reconstruction
    char_length     INTEGER,
    fragment_text   TEXT NOT NULL,
    content_hash    TEXT NOT NULL,          -- SHA-1 of normalized fragment text
    UNIQUE(version_id, fragment_index)
);
CREATE INDEX IF NOT EXISTS idx_frag_bill    ON bill_language_fragments(bill_pk);
CREATE INDEX IF NOT EXISTS idx_frag_session ON bill_language_fragments(session_id);
CREATE INDEX IF NOT EXISTS idx_frag_hash    ON bill_language_fragments(content_hash);

-- ─────────────────────────────────────────────────────────────────────────────
-- LANGUAGE LINEAGE  (extends bill_lineage with fragment-level and authorship)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS language_lineage (
    lang_lineage_id         INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Source: where the language originated
    source_bill_pk          INTEGER NOT NULL REFERENCES bills(bill_pk),
    source_version_id       INTEGER REFERENCES bill_versions(version_id),
    source_fragment_id      INTEGER REFERENCES bill_language_fragments(fragment_id),
    source_session_id       TEXT NOT NULL,
    source_member_id        INTEGER REFERENCES members(member_id),   -- primary sponsor

    -- Target: where the language reappears
    target_bill_pk          INTEGER NOT NULL REFERENCES bills(bill_pk),
    target_version_id       INTEGER REFERENCES bill_versions(version_id),
    target_fragment_id      INTEGER REFERENCES bill_language_fragments(fragment_id),
    target_session_id       TEXT NOT NULL,
    target_member_id        INTEGER REFERENCES members(member_id),   -- primary sponsor

    -- Match characteristics
    match_type              TEXT NOT NULL
        CHECK(match_type IN (
            'reintroduced',       -- whole bill, new session
            'amendment_adopted',  -- language added to another bill
            'partial_reuse',      -- section/passage reused
            'substitute',         -- bill replaced by similar language
            'zombie'              -- failed bill reappears later
        )),
    granularity             TEXT NOT NULL CHECK(granularity IN ('bill','section','passage')),
    similarity_score        REAL NOT NULL,      -- Jaccard (whole-bill) or containment (partial)
    containment_score       REAL,               -- |A∩B|/|A| — how much of source is in target
    method                  TEXT NOT NULL
        CHECK(method IN ('minhash','jaccard','containment','exact_hash','hybrid','manual')),

    -- Attribution chain (denormalized for query speed)
    all_source_member_ids   TEXT,   -- JSON array: primary + cosponsors of source bill
    all_target_member_ids   TEXT,   -- JSON array: primary + cosponsors of target bill

    detected_at             TEXT NOT NULL,
    confirmed               INTEGER,    -- NULL=auto / 1=human confirmed / 0=rejected
    confirmed_by            TEXT,
    note                    TEXT,

    UNIQUE(source_bill_pk, target_bill_pk, source_fragment_id, target_fragment_id)
);
CREATE INDEX IF NOT EXISTS idx_ll_source_bill    ON language_lineage(source_bill_pk);
CREATE INDEX IF NOT EXISTS idx_ll_target_bill    ON language_lineage(target_bill_pk);
CREATE INDEX IF NOT EXISTS idx_ll_source_session ON language_lineage(source_session_id);
CREATE INDEX IF NOT EXISTS idx_ll_target_session ON language_lineage(target_session_id);
CREATE INDEX IF NOT EXISTS idx_ll_source_member  ON language_lineage(source_member_id);
CREATE INDEX IF NOT EXISTS idx_ll_target_member  ON language_lineage(target_member_id);
CREATE INDEX IF NOT EXISTS idx_ll_match_type     ON language_lineage(match_type);
CREATE INDEX IF NOT EXISTS idx_ll_containment    ON language_lineage(containment_score DESC);